version: '3.7'

services:
  transcription-service:
    image: transcription_service:1.2.3
    volumes:
      - $SHARED_FOLDER/audio:/opt/audio
    env_file: .env
    ports:
      - "$SERVINGPORT:80"
    networks:
      - transcription-net

networks:
  transcription-net:
    external: true



