version: '3.5'

services:
  transcription-service:
    build: .
    container_name: ${SERVICE_NAME}_transcription_service
    image: linto-platform-transcription-service:latest
    volumes:
      - ${RESSOURCE_FOLDER}:/opt/audio
    env_file: .env
    ports:
      - target: 80
        published: ${TRANSCRIPTION_API_PORT}
    expose: 
      - "80"
  