openapi: 3.0.1
info:
  title: Transcription service
  description: Transcription request interface
  version: 1.0.0
servers:
- url: /
paths:
  /transcribe:
    post:
      tags:
      - Speech-To-Text API
      summary: Perform Speech-to-Text
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                transcriptionConfig:
                  type: object
                  $ref: '#/components/schemas/transcriptionConfig'
                force_sync:
                  type: boolean
                  default: false
      responses:
        200:
          description: "Job successfully finished (force_sync)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transcriptionResult'
            text/plain:
              schema:
                type: string
                default: This is a transcription
            text/vtt:
              schema:
                type: string
                default: Return the transcription as VTT subtitles.
            text/srt:
              schema:
                type: string
                default: Return the transcription as SRT subtitles.
        201:
          description: Successfully created transcription job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobID'
        400:
          description: "Bad request"
          content:
            text/plain:
              schema:
                type: string
                default: "Bad header / Bad parameters / No file attached"
        500:
          description: "Server error"
          content:
            text/plain:
              schema:
                type: string
                default: "The server encountered an unexpected error."
        
  /job/{jobid}:
    get:
      tags:
        - Job status
      parameters:
        - name: "jobid"
          in: path
          required: true
          description: Job request ID
          schema:
            type: string

      responses:
        201:
          description: "Job successfully finished. Returns a result ID"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobFinished'
        202:
          description: Task is still processing. Return job progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobInProgress'
        400:
          description: Task has failed
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/jobFailed'


        404:
          description: JobId hasn't been found
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/jobUnknown'
  
  /results/{result_id}:
    get:
      tags:
        - Transcription result
      parameters:
        - name: result_id
          in: path
          required: true
          description: Result id
          schema:
            type: string
      responses:
        200:
          description: Ressource available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transcriptionResult'
            text/plain:
              schema:
                type: string
                default: This is a transcription
            text/vtt:
              schema:
                type: string
                default: Return the transcription as VTT subtitles.
            text/srt:
              schema:
                type: string
                default: Return the transcription as SRT subtitles.
        404:
          description: No ressource found for this id

components:
  schemas:
    transcriptionConfig:
      type: object
      properties:
        transcribePerChannel:
          type: boolean
          default: false
        enablePunctuation:
          type: boolean
          default: false
        diarizationConfig:
          type: object
          $ref: '#/components/schemas/diarizationConfig'

    diarizationConfig:
      type: object
      properties:
        enableDiarization:
          type: boolean
          default: false
        numberOfSpeaker:
          type: integer
          default: null
        maxNumberOfSpeaker:
          type: integer
          default: null
    jobID:
      type: object
      properties:
        jobid:
          type: string
    jobInProgress:
      type: object
      properties:
        state:
          type: string
          enum: [started, pending]
        progress:
          type: object
    jobFinished:
      type: object
      properties:
        state:
          type: string
          default: finished
        ressource_id:
          type: string
          default: "ressource_id to use on the /results/{ressource_id} route"
    jobUnknown:
      type: object
      properties:
        state:
          type: string
          default: "unknown"
    jobFailed:
      type: object
      properties:
        state:
          type: string
          default: "failed"
        reason:
          type: string
          default: "The server encountered an error"
    transcriptionResult:
      type: object
      properties:
        transcription_result:
          type: string
        confidence:
          type: number
        raw_transcription:
          type: string
        segments:
          type: array
          items:
            $ref: '#/components/schemas/speechSegment'
    speechSegment:
      type: object
      properties:
        spk_id: 
          type: string
        start: 
          type: number
        end: 
          type: number
        duration: 
          type: number
        segment: 
          type: string
        raw_segment:
          type: string
        words:
          type: array
          items:
            $ref: '#/components/schemas/word'
    word:
      type: object
      properties:
        start:
          type: number
        end:
          type: number
        word:
          type: string
        confidence:
          type: number


